"""微信小店表结构定义。"""

# 订单表：中文列名 -> 英文字段名
ORDER_COLUMN_MAPPING = {
    '订单号': 'order_no',
    '订单下单时间': 'order_created_at',
    '订单发货时间': 'order_shipped_at',
    '订单确认收货时间': 'order_received_at',
    '订单完成结算时间': 'order_settled_at',
    '订单状态': 'order_status',
    '发货方式': 'delivery_method',
    '收件人姓名': 'recipient_name',
    '收件人地址': 'recipient_address',
    '省': 'province',
    '市': 'city',
    '区': 'district',
    '收件人手机': 'recipient_phone',
    '买家备注': 'buyer_note',
    '商家备注': 'seller_note',
    '打标颜色': 'label_color',
    '商品总价': 'product_total_amount',
    '订单实付支付金额': 'order_paid_amount',
    '订单实际支付金额': 'order_paid_amount',
    '订单实际收款金额': 'order_received_amount',
    '订单运费': 'order_shipping_fee',
    '商品优惠': 'product_discount_amount',
    '跨店优惠': 'cross_store_discount_amount',
    '商品改价': 'product_price_adjustment',
    '积分抵扣': 'points_deduction_amount',
    '支付方式': 'payment_method',
    '支付时间': 'payment_at',
    '交易单号': 'transaction_no',
    '物流公司': 'logistics_company',
    '快递单号': 'tracking_no',
    '技术服务费': 'technical_service_fee',
    '技术服务费(将以人气卡形式返还)': 'technical_service_fee_refund_popularity_card',
    '运费险预计投保费用': 'shipping_insurance_estimated_fee',
    '带货方式': 'promotion_method',
    '带货账号类型': 'promotion_account_type',
    '带货账号昵称': 'promotion_account_nickname',
    '带货费用类型': 'promotion_fee_type',
    '带货费用': 'promotion_fee_amount',
    '带货费用渠道': 'promotion_fee_channel',
    '带货佣金率': 'promotion_commission_rate',
    '礼物单号': 'gift_order_no',
    '商品名称': 'product_name',
    '商品编码（平台）': 'platform_product_code',
    '商品编码(自定义)': 'custom_product_code',
    'SKU编码(自定义)': 'custom_sku_code',
    '商品属性': 'product_attributes',
    '商品价格(单件)': 'product_unit_price',
    '商品实际价格(单件)': 'product_actual_unit_price',
    '商品实际价格(总共)': 'product_actual_total_price',
    '是否预售': 'is_presale',
    '商品数量': 'product_quantity',
    '商品平台券优惠': 'platform_coupon_discount_amount',
    '商品平均运费': 'average_shipping_fee_per_item',
    '定制信息': 'customization_info',
    '定制预览图': 'customization_preview_image',
    '商品发货': 'product_delivery_status',
    '商品售后': 'product_after_sales_status',
    '商品已退款金额': 'product_refunded_amount',
}

# 第一次导入和后续处理都必须存在的关键字段
ORDER_REQUIRED_COLUMNS = [
    '订单号',
    '订单下单时间',
    '商品编码（平台）',
    '商品数量',
]

# 建表时可参考的字段类型（SQLite 第一版）
ORDER_COLUMN_TYPES = {
    'order_no': 'TEXT',
    'order_created_at': 'TEXT',
    'order_shipped_at': 'TEXT',
    'order_received_at': 'TEXT',
    'order_settled_at': 'TEXT',
    'order_status': 'TEXT',
    'delivery_method': 'TEXT',
    'recipient_name': 'TEXT',
    'recipient_address': 'TEXT',
    'province': 'TEXT',
    'city': 'TEXT',
    'district': 'TEXT',
    'recipient_phone': 'TEXT',
    'buyer_note': 'TEXT',
    'seller_note': 'TEXT',
    'label_color': 'TEXT',
    'product_total_amount': 'REAL',
    'order_paid_amount': 'REAL',
    'order_received_amount': 'REAL',
    'order_shipping_fee': 'REAL',
    'product_discount_amount': 'REAL',
    'cross_store_discount_amount': 'REAL',
    'product_price_adjustment': 'REAL',
    'points_deduction_amount': 'REAL',
    'payment_method': 'TEXT',
    'payment_at': 'TEXT',
    'transaction_no': 'TEXT',
    'logistics_company': 'TEXT',
    'tracking_no': 'TEXT',
    'technical_service_fee': 'REAL',
    'technical_service_fee_refund_popularity_card': 'REAL',
    'shipping_insurance_estimated_fee': 'REAL',
    'promotion_method': 'TEXT',
    'promotion_account_type': 'TEXT',
    'promotion_account_nickname': 'TEXT',
    'promotion_fee_type': 'TEXT',
    'promotion_fee_amount': 'REAL',
    'promotion_fee_channel': 'TEXT',
    'promotion_commission_rate': 'REAL',
    'gift_order_no': 'TEXT',
    'product_name': 'TEXT',
    'platform_product_code': 'TEXT',
    'custom_product_code': 'TEXT',
    'custom_sku_code': 'TEXT',
    'product_attributes': 'TEXT',
    'product_unit_price': 'REAL',
    'product_actual_unit_price': 'REAL',
    'product_actual_total_price': 'REAL',
    'is_presale': 'TEXT',
    'product_quantity': 'INTEGER',
    'platform_coupon_discount_amount': 'REAL',
    'average_shipping_fee_per_item': 'REAL',
    'customization_info': 'TEXT',
    'customization_preview_image': 'TEXT',
    'product_delivery_status': 'TEXT',
    'product_after_sales_status': 'TEXT',
    'product_refunded_amount': 'REAL',
}

# 数据库订单表名（第一版先固定）
WECHAT_ORDER_TABLE_NAME = 'wechat_orders'

# ==================== 资金流水表 ====================

FUND_FLOW_COLUMN_MAPPING = {
    '流水单号': 'flow_no',
    '记账时间': 'booking_time',
    '动帐类型': 'transaction_type',
    '收支类型': 'income_expense_type',
    '收支金额': 'amount',
    '账户余额': 'account_balance',
    '关联订单号': 'related_order_no',
    '关联售后单号': 'related_after_sales_no',
    '关联提现单号': 'related_withdrawal_no',
    '关联保单号': 'related_policy_no',
    '关联礼物单号': 'related_gift_no',
    '详情': 'detail',
}

FUND_FLOW_REQUIRED_COLUMNS = [
    '流水单号',
    '记账时间',
    '动帐类型',
    '关联订单号',
]

FUND_FLOW_COLUMN_TYPES = {
    'flow_no': 'TEXT',
    'booking_time': 'TEXT',
    'transaction_type': 'TEXT',
    'income_expense_type': 'TEXT',
    'amount': 'REAL',
    'account_balance': 'REAL',
    'related_order_no': 'TEXT',
    'related_after_sales_no': 'TEXT',
    'related_withdrawal_no': 'TEXT',
    'related_policy_no': 'TEXT',
    'related_gift_no': 'TEXT',
    'detail': 'TEXT',
}

WECHAT_FUND_FLOW_TABLE_NAME = 'wechat_fund_flow'

# ==================== 售后表 ====================

AFTER_SALES_COLUMN_MAPPING = {
    '售后单号': 'after_sales_no',
    '售后申请时间': 'after_sales_apply_time',
    '商品编码（平台）': 'platform_product_code',
    '商品编码(自定义)': 'custom_product_code',
    'SKU编码(自定义)': 'custom_sku_code',
    'sku编码(自定义)': 'custom_sku_code',
    '同意售后申请时间': 'after_sales_approved_time',
    '用户到账时间': 'user_received_time',
    '售后完结时间': 'after_sales_finished_time',
    '订单编号': 'order_no',
    '发货状态': 'delivery_status',
    '商品名称': 'product_name',
    '商品描述': 'product_description',
    '商品价格': 'product_price',
    '申请售后数量': 'after_sales_quantity',
    '赠品信息': 'gift_info',
    '备注': 'remark',
    '实付款': 'paid_amount',
    '退款类型': 'refund_type',
    '退款原因': 'refund_reason',
    '具体描述': 'detailed_description',
    '退款金额': 'refund_amount',
    '退款状态': 'refund_status',
    '状态描述': 'status_description',
    '平台纠纷介入': 'platform_dispute_intervention',
    '纠纷责任': 'dispute_responsibility',
    '执行方式': 'execution_method',
    '发货物流状态': 'delivery_logistics_status',
    '发货物流单号': 'delivery_tracking_no',
    '发货物流公司': 'delivery_logistics_company',
    '用户退换货发货时间': 'user_return_shipped_time',
    '商家换货发货时间': 'merchant_exchange_shipped_time',
    '商家退换货地址': 'merchant_return_address',
    '商家退换货联系人姓名': 'merchant_contact_name',
    '商家退换货联系人电话': 'merchant_contact_phone',
    '退换货物流状态': 'return_logistics_status',
    '退换货物流单号': 'return_tracking_no',
    '退换货物流公司': 'return_logistics_company',
}

AFTER_SALES_REQUIRED_COLUMNS = [
    '售后单号',
    '售后申请时间',
]

AFTER_SALES_COLUMN_TYPES = {
    'after_sales_no': 'TEXT',
    'after_sales_apply_time': 'TEXT',
    'platform_product_code': 'TEXT',
    'custom_product_code': 'TEXT',
    'custom_sku_code': 'TEXT',
    'after_sales_approved_time': 'TEXT',
    'user_received_time': 'TEXT',
    'after_sales_finished_time': 'TEXT',
    'order_no': 'TEXT',
    'delivery_status': 'TEXT',
    'product_name': 'TEXT',
    'product_description': 'TEXT',
    'product_price': 'REAL',
    'after_sales_quantity': 'INTEGER',
    'gift_info': 'TEXT',
    'remark': 'TEXT',
    'paid_amount': 'REAL',
    'refund_type': 'TEXT',
    'refund_reason': 'TEXT',
    'detailed_description': 'TEXT',
    'refund_amount': 'REAL',
    'refund_status': 'TEXT',
    'status_description': 'TEXT',
    'platform_dispute_intervention': 'TEXT',
    'dispute_responsibility': 'TEXT',
    'execution_method': 'TEXT',
    'delivery_logistics_status': 'TEXT',
    'delivery_tracking_no': 'TEXT',
    'delivery_logistics_company': 'TEXT',
    'user_return_shipped_time': 'TEXT',
    'merchant_exchange_shipped_time': 'TEXT',
    'merchant_return_address': 'TEXT',
    'merchant_contact_name': 'TEXT',
    'merchant_contact_phone': 'TEXT',
    'return_logistics_status': 'TEXT',
    'return_tracking_no': 'TEXT',
    'return_logistics_company': 'TEXT',
}

WECHAT_AFTER_SALES_TABLE_NAME = 'wechat_after_sales'
