"""抖音店铺四张表的字段定义（两个店铺共用）。"""

# ==================== 订单表 ====================

ORDERS_COLUMN_MAPPING = {
    '主订单编号': 'main_order_no',
    '子订单编号': 'sub_order_no',
    '选购商品': 'product_name',
    '商品规格': 'product_spec',
    '商品数量': 'product_quantity',
    '商品ID': 'product_id',
    '商家编码': 'merchant_code',
    '商品单价': 'product_unit_price',
    '订单应付金额': 'order_payable_amount',
    '运费': 'shipping_fee',
    '优惠总金额': 'total_discount_amount',
    '平台优惠': 'platform_discount',
    '商家优惠': 'merchant_discount',
    '达人优惠': 'influencer_discount',
    '商家改价': 'merchant_price_adjustment',
    '支付优惠': 'payment_discount',
    '红包抵扣': 'hongbao_deduction',
    '支付方式': 'payment_method',
    '手续费': 'handling_fee',
    '收件人': 'recipient_name',
    '收件人手机号': 'recipient_phone',
    '省': 'province',
    '市': 'city',
    '区': 'district',
    '街道': 'street',
    '详细地址': 'detailed_address',
    '是否修改过地址': 'address_modified',
    '地址修改时段': 'address_modify_period',
    '买家留言': 'buyer_note',
    '订单提交时间': 'order_submitted_at',
    '旗帜颜色': 'flag_color',
    '商家备注': 'seller_note',
    '订单完成时间': 'order_completed_at',
    '支付完成时间': 'payment_completed_at',
    'APP渠道': 'app_channel',
    '流量来源': 'traffic_source',
    '订单状态': 'order_status',
    '承诺发货时间': 'promised_shipping_at',
    '订单类型': 'order_type',
    '鲁班落地页ID': 'luban_landing_page_id',
    '达人ID': 'influencer_id',
    '达人昵称': 'influencer_nickname',
    '所属门店ID': 'store_id',
    '售后状态': 'after_sales_status',
    '取消原因': 'cancel_reason',
    '预约发货时间': 'reserved_shipping_at',
    '仓库ID': 'warehouse_id',
    '仓库名称': 'warehouse_name',
    '是否安心购': 'is_secure_purchase',
    '广告渠道': 'ad_channel',
    '流量类型': 'traffic_type',
    '流量体裁': 'traffic_format',
    '流量渠道': 'traffic_channel',
    '发货主体': 'shipping_entity',
    '发货主体明细': 'shipping_entity_detail',
    '发货时间': 'shipped_at',
    '降价类优惠': 'markdown_discount',
    '平台实际承担优惠金额': 'platform_actual_discount',
    '商家实际承担优惠金额': 'merchant_actual_discount',
    '达人实际承担优惠金额': 'influencer_actual_discount',
    '预计送达时间': 'estimated_delivery_at',
    '是否平台仓自流转': 'is_platform_warehouse_transfer',
    '车型': 'vehicle_type',
    '商品69码': 'product_barcode',
    '发货SN码': 'shipping_sn_code',
    '发货IMEI码1': 'shipping_imei1',
    '发货IMEI码2': 'shipping_imei2',
    '预约送达时间': 'reserved_delivery_at',
    '建议发货时间（起）': 'suggested_ship_start_at',
    '建议发货时间（止）': 'suggested_ship_end_at',
    '物流SN码': 'logistics_sn_code',
    '物流IMEI码1': 'logistics_imei1',
    '物流IMEI码2': 'logistics_imei2',
}

ORDERS_COLUMN_TYPES = {
    'main_order_no': 'TEXT',
    'sub_order_no': 'TEXT',
    'product_name': 'TEXT',
    'product_spec': 'TEXT',
    'product_quantity': 'INTEGER',
    'product_id': 'TEXT',
    'merchant_code': 'TEXT',
    'product_unit_price': 'REAL',
    'order_payable_amount': 'REAL',
    'shipping_fee': 'REAL',
    'total_discount_amount': 'REAL',
    'platform_discount': 'TEXT',
    'merchant_discount': 'TEXT',
    'influencer_discount': 'TEXT',
    'merchant_price_adjustment': 'REAL',
    'payment_discount': 'REAL',
    'hongbao_deduction': 'REAL',
    'payment_method': 'TEXT',
    'handling_fee': 'REAL',
    'recipient_name': 'TEXT',
    'recipient_phone': 'TEXT',
    'province': 'TEXT',
    'city': 'TEXT',
    'district': 'TEXT',
    'street': 'TEXT',
    'detailed_address': 'TEXT',
    'address_modified': 'TEXT',
    'address_modify_period': 'TEXT',
    'buyer_note': 'TEXT',
    'order_submitted_at': 'TEXT',
    'flag_color': 'TEXT',
    'seller_note': 'TEXT',
    'order_completed_at': 'TEXT',
    'payment_completed_at': 'TEXT',
    'app_channel': 'TEXT',
    'traffic_source': 'TEXT',
    'order_status': 'TEXT',
    'promised_shipping_at': 'TEXT',
    'order_type': 'TEXT',
    'luban_landing_page_id': 'TEXT',
    'influencer_id': 'TEXT',
    'influencer_nickname': 'TEXT',
    'store_id': 'TEXT',
    'after_sales_status': 'TEXT',
    'cancel_reason': 'TEXT',
    'reserved_shipping_at': 'TEXT',
    'warehouse_id': 'TEXT',
    'warehouse_name': 'TEXT',
    'is_secure_purchase': 'TEXT',
    'ad_channel': 'TEXT',
    'traffic_type': 'TEXT',
    'traffic_format': 'TEXT',
    'traffic_channel': 'TEXT',
    'shipping_entity': 'TEXT',
    'shipping_entity_detail': 'TEXT',
    'shipped_at': 'TEXT',
    'markdown_discount': 'REAL',
    'platform_actual_discount': 'REAL',
    'merchant_actual_discount': 'REAL',
    'influencer_actual_discount': 'REAL',
    'estimated_delivery_at': 'TEXT',
    'is_platform_warehouse_transfer': 'TEXT',
    'vehicle_type': 'TEXT',
    'product_barcode': 'TEXT',
    'shipping_sn_code': 'TEXT',
    'shipping_imei1': 'TEXT',
    'shipping_imei2': 'TEXT',
    'reserved_delivery_at': 'TEXT',
    'suggested_ship_start_at': 'TEXT',
    'suggested_ship_end_at': 'TEXT',
    'logistics_sn_code': 'TEXT',
    'logistics_imei1': 'TEXT',
    'logistics_imei2': 'TEXT',
}

ORDERS_REQUIRED_COLUMNS = ['主订单编号', '子订单编号', '选购商品', '订单状态']
ORDERS_DEDUP_KEY_COLUMNS = ['sub_order_no']

# 防止长数字被科学计数法处理的字段（CSV/xlsx 读入时 dtype='string'）
ORDERS_TEXT_SOURCE_COLUMNS = {
    '主订单编号', '子订单编号', '商品ID', '商家编码',
    '鲁班落地页ID', '达人ID', '所属门店ID', '仓库ID', '收件人手机号',
}

OVERSEAS_ORDERS_COLUMN_MAPPING = dict(ORDERS_COLUMN_MAPPING)
OVERSEAS_ORDERS_COLUMN_MAPPING.update({
    '货品ID': 'sku_id',
    '序列号': 'serial_no',
    '商品单价是否含税': 'is_product_unit_price_tax_included',
    '税费': 'tax_fee',
})

OVERSEAS_ORDERS_COLUMN_TYPES = dict(ORDERS_COLUMN_TYPES)
OVERSEAS_ORDERS_COLUMN_TYPES.update({
    'sku_id': 'TEXT',
    'serial_no': 'TEXT',
    'is_product_unit_price_tax_included': 'TEXT',
    'tax_fee': 'REAL',
})

OVERSEAS_ORDERS_REQUIRED_COLUMNS = ORDERS_REQUIRED_COLUMNS
OVERSEAS_ORDERS_DEDUP_KEY_COLUMNS = ORDERS_DEDUP_KEY_COLUMNS

OVERSEAS_ORDERS_TEXT_SOURCE_COLUMNS = set(ORDERS_TEXT_SOURCE_COLUMNS) | {
    '货品ID', '序列号',
}

# ==================== 资金结算表 ====================

FUND_FLOW_COLUMN_MAPPING = {
    '结算时间': 'settlement_time',
    '订单号': 'order_no',
    '子订单号': 'sub_order_no',
    '结算金额': 'settlement_amount',
    '结算账户': 'settlement_account',
    '结算单类型': 'settlement_type',
    '有结算前退款': 'has_presettlement_refund',
    '下单时间': 'order_created_at',
    '商品ID': 'product_id',
    '商品名称': 'product_name',
    '商品数量': 'product_quantity',
    '达人ID': 'influencer_id',
    '达人名称': 'influencer_name',
    '业务类型': 'business_type',
    '订单类型': 'order_type',
    '订单总价': 'order_total_price',
    '商品总价': 'product_total_price',
    '运费': 'shipping_fee',
    '店铺券': 'store_coupon',
    '政府补贴商家垫资': 'gov_subsidy_merchant_advance',
    '结算前退款金额': 'presettlement_refund_amount',
    '平台补贴': 'platform_subsidy',
    '其他平台补贴': 'other_platform_subsidy',
    '政府补贴平台垫资': 'gov_subsidy_platform_advance',
    '达人补贴': 'influencer_subsidy',
    '抖音支付补贴': 'douyin_pay_subsidy',
    '抖音月付营销补贴': 'douyin_monthly_pay_subsidy',
    '银行补贴': 'bank_subsidy',
    '以旧换新抵扣': 'trade_in_deduction',
    '平台补贴运费': 'platform_subsidy_shipping',
    '用户实付': 'user_actual_paid',
    '收入合计': 'total_income',
    '平台服务费': 'platform_service_fee',
    '达人佣金': 'influencer_commission',
    '服务商佣金': 'service_provider_commission',
    '渠道分成': 'channel_share',
    '招商服务费': 'merchant_recruitment_fee',
    '站外推广费': 'external_promotion_fee',
    '其他分成': 'other_share',
    '其他分成说明': 'other_share_note',
    '支出合计': 'total_expense',
    '是否免佣': 'is_commission_exempt',
    '免佣金额': 'commission_exempt_amount',
    '商户主体名称': 'merchant_entity_name',
    '备注': 'notes',
}

FUND_FLOW_COLUMN_TYPES = {
    'settlement_time': 'TEXT',
    'order_no': 'TEXT',
    'sub_order_no': 'TEXT',
    'settlement_amount': 'REAL',
    'settlement_account': 'TEXT',
    'settlement_type': 'TEXT',
    'has_presettlement_refund': 'TEXT',
    'order_created_at': 'TEXT',
    'product_id': 'TEXT',
    'product_name': 'TEXT',
    'product_quantity': 'INTEGER',
    'influencer_id': 'TEXT',
    'influencer_name': 'TEXT',
    'business_type': 'TEXT',
    'order_type': 'TEXT',
    'order_total_price': 'REAL',
    'product_total_price': 'REAL',
    'shipping_fee': 'REAL',
    'store_coupon': 'REAL',
    'gov_subsidy_merchant_advance': 'REAL',
    'presettlement_refund_amount': 'REAL',
    'platform_subsidy': 'REAL',
    'other_platform_subsidy': 'REAL',
    'gov_subsidy_platform_advance': 'REAL',
    'influencer_subsidy': 'REAL',
    'douyin_pay_subsidy': 'REAL',
    'douyin_monthly_pay_subsidy': 'REAL',
    'bank_subsidy': 'REAL',
    'trade_in_deduction': 'REAL',
    'platform_subsidy_shipping': 'REAL',
    'user_actual_paid': 'REAL',
    'total_income': 'REAL',
    'platform_service_fee': 'REAL',
    'influencer_commission': 'REAL',
    'service_provider_commission': 'REAL',
    'channel_share': 'REAL',
    'merchant_recruitment_fee': 'REAL',
    'external_promotion_fee': 'REAL',
    'other_share': 'REAL',
    'other_share_note': 'TEXT',
    'total_expense': 'REAL',
    'is_commission_exempt': 'TEXT',
    'commission_exempt_amount': 'REAL',
    'merchant_entity_name': 'TEXT',
    'notes': 'TEXT',
}

FUND_FLOW_REQUIRED_COLUMNS = ['结算时间', '订单号', '子订单号']
FUND_FLOW_DEDUP_KEY_COLUMNS = ['order_no', 'sub_order_no', 'settlement_time', 'settlement_type']

FUND_FLOW_TEXT_SOURCE_COLUMNS = {
    '订单号', '子订单号', '商品ID', '达人ID',
}

OVERSEAS_FUND_FLOW_COLUMN_MAPPING = {
    '动账时间': 'settlement_time',
    '动账流水号': 'transaction_no',
    '动账方向': 'transaction_direction',
    '动账账户': 'transaction_account',
    '动账金额': 'transaction_amount',
    '动账摘要': 'settlement_type',
    '订单号': 'order_no',
    '子订单号': 'sub_order_no',
    '下单时间': 'order_created_at',
    '商品ID': 'product_id',
    '税费': 'tax_fee',
    '业务类型': 'business_type',
    '结算金额(元)': 'settlement_amount',
    '汇率': 'exchange_rate',
    '币种': 'currency',
    '结算外币金额': 'foreign_settlement_amount',
    '订单实付(元)': 'user_actual_paid',
    '达人补贴(元)': 'influencer_subsidy',
    '平台补贴(元)': 'platform_subsidy',
    '平台补贴外币金额': 'platform_subsidy_foreign_amount',
    '退款(元)': 'refund_amount',
    '平台服务费(元)': 'platform_service_fee',
    '佣金(元)': 'influencer_commission',
    '招商服务费(元)': 'merchant_recruitment_fee',
    '供应链费用(元)': 'supply_chain_fee',
    '预留税费(元)': 'reserved_tax_fee',
    '站外推广费(元)': 'external_promotion_fee',
    '供应链欠款抵扣(元)': 'supply_chain_debt_deduction',
    '分期服务费(元)': 'installment_service_fee',
    '是否免佣': 'is_commission_exempt',
    '免佣金额': 'commission_exempt_amount',
}

OVERSEAS_FUND_FLOW_COLUMN_TYPES = dict(FUND_FLOW_COLUMN_TYPES)
OVERSEAS_FUND_FLOW_COLUMN_TYPES.update({
    'transaction_no': 'TEXT',
    'transaction_direction': 'TEXT',
    'transaction_account': 'TEXT',
    'transaction_amount': 'REAL',
    'tax_fee': 'REAL',
    'exchange_rate': 'REAL',
    'currency': 'TEXT',
    'foreign_settlement_amount': 'REAL',
    'platform_subsidy_foreign_amount': 'REAL',
    'refund_amount': 'REAL',
    'supply_chain_fee': 'REAL',
    'reserved_tax_fee': 'REAL',
    'supply_chain_debt_deduction': 'REAL',
    'installment_service_fee': 'REAL',
})

OVERSEAS_FUND_FLOW_REQUIRED_COLUMNS = ['动账时间', '动账流水号', '订单号', '子订单号']
OVERSEAS_FUND_FLOW_DEDUP_KEY_COLUMNS = ['transaction_no']

OVERSEAS_FUND_FLOW_TEXT_SOURCE_COLUMNS = {
    '动账流水号', '动账账户', '订单号', '子订单号', '商品ID',
}

# ==================== 佣金订单明细表 ====================

COMMISSION_COLUMN_MAPPING = {
    '订单id': 'order_id',
    '商品id': 'product_id',
    '商品名称': 'product_name',
    '作者账号': 'author_account',
    '抖音/火山号': 'douyin_id',
    '支付金额': 'paid_amount',
    '佣金率': 'commission_rate',
    '预估佣金支出': 'estimated_commission',
    '结算金额': 'settlement_amount',
    '实际佣金支出': 'actual_commission',
    '订单状态': 'order_status',
    '超时未结算原因': 'unsettled_reason',
    '付款时间': 'payment_time',
    '收货时间': 'received_time',
    '订单结算时间': 'settlement_time',
    '商品来源': 'product_source',
    '尾款支付时间': 'final_payment_time',
    '定金金额': 'deposit_amount',
    '店铺id': 'store_id',
    '店铺名称': 'store_name',
    '商品数量': 'product_quantity',
    '佣金发票': 'commission_invoice',
    '冻结比例': 'frozen_ratio',
    '是否阶梯佣金': 'is_tiered_commission',
    '门槛销量': 'threshold_sales',
    '基础佣金率': 'base_commission_rate',
    '升佣佣金率': 'upgraded_commission_rate',
    '预估奖励佣金支出': 'estimated_reward_commission',
    '结算奖励佣金支出': 'settled_reward_commission',
    '阶梯计划ID': 'tiered_plan_id',
    '支付补贴': 'payment_subsidy',
    '平台补贴': 'platform_subsidy',
    '达人补贴': 'influencer_subsidy',
    '运费': 'shipping_fee',
    '税费': 'tax_fee',
    '运费补贴': 'shipping_subsidy',
    '分销来源': 'distribution_source',
    '营销活动id': 'campaign_id',
    '推广费率': 'promotion_rate',
    '推广技术服务费': 'promotion_tech_service_fee',
    '预估推广费支出': 'estimated_promotion_expense',
    '结算推广费支出': 'settled_promotion_expense',
    '佣金类型': 'commission_type',
    '订单来源': 'order_source',
    '流量细分来源': 'traffic_subsource',
    '流量来源': 'traffic_source',
    '订单类型': 'order_type',
}

COMMISSION_COLUMN_TYPES = {
    'order_id': 'TEXT',
    'product_id': 'TEXT',
    'product_name': 'TEXT',
    'author_account': 'TEXT',
    'douyin_id': 'TEXT',
    'paid_amount': 'REAL',
    'commission_rate': 'TEXT',
    'estimated_commission': 'REAL',
    'settlement_amount': 'REAL',
    'actual_commission': 'REAL',
    'order_status': 'TEXT',
    'unsettled_reason': 'TEXT',
    'payment_time': 'TEXT',
    'received_time': 'TEXT',
    'settlement_time': 'TEXT',
    'product_source': 'TEXT',
    'final_payment_time': 'TEXT',
    'deposit_amount': 'REAL',
    'store_id': 'TEXT',
    'store_name': 'TEXT',
    'product_quantity': 'INTEGER',
    'commission_invoice': 'TEXT',
    'frozen_ratio': 'TEXT',
    'is_tiered_commission': 'TEXT',
    'threshold_sales': 'INTEGER',
    'base_commission_rate': 'TEXT',
    'upgraded_commission_rate': 'TEXT',
    'estimated_reward_commission': 'REAL',
    'settled_reward_commission': 'REAL',
    'tiered_plan_id': 'TEXT',
    'payment_subsidy': 'REAL',
    'platform_subsidy': 'REAL',
    'influencer_subsidy': 'REAL',
    'shipping_fee': 'REAL',
    'tax_fee': 'REAL',
    'shipping_subsidy': 'REAL',
    'distribution_source': 'TEXT',
    'campaign_id': 'TEXT',
    'promotion_rate': 'TEXT',
    'promotion_tech_service_fee': 'REAL',
    'estimated_promotion_expense': 'REAL',
    'settled_promotion_expense': 'REAL',
    'commission_type': 'TEXT',
    'order_source': 'TEXT',
    'traffic_subsource': 'TEXT',
    'traffic_source': 'TEXT',
    'order_type': 'TEXT',
}

COMMISSION_REQUIRED_COLUMNS = ['订单id', '商品id', '订单结算时间']
COMMISSION_DEDUP_KEY_COLUMNS = ['order_id', 'product_id', 'settlement_time', 'commission_type']

COMMISSION_TEXT_SOURCE_COLUMNS = {
    '订单id', '商品id', '店铺id', '营销活动id', '阶梯计划ID',
}

# ==================== 招商订单明细表 ====================
# 注意：原始xlsx第21列和第30列均为"订单来源"（平台命名重复）
# pandas读取时会将第二个重复列名自动改为"订单来源.1"
# 分别存为 order_source_purchase（购买侧）和 order_source_traffic（流量侧）

MERCHANT_COLUMN_MAPPING = {
    '订单id': 'order_id',
    '商品名称': 'product_name',
    '商品id': 'product_id',
    '订单状态': 'order_status',
    '超时未结算原因': 'unsettled_reason',
    '出单机构': 'issuing_institution',
    '支付金额': 'paid_amount',
    '服务费率': 'service_fee_rate',
    '预估服务费收入': 'estimated_service_income',
    '结算金额': 'settlement_amount',
    '实际服务费收入': 'actual_service_income',
    '付款时间': 'payment_time',
    '收货时间': 'received_time',
    '结算时间': 'settlement_time',
    '尾款支付时间': 'final_payment_time',
    '定金金额': 'deposit_amount',
    '店铺id': 'store_id',
    '店铺名称': 'store_name',
    '商品数量': 'product_quantity',
    '团长活动id': 'group_campaign_id',
    '订单来源': 'order_source_purchase',
    '支付补贴': 'payment_subsidy',
    '平台补贴': 'platform_subsidy',
    '达人补贴': 'influencer_subsidy',
    '运费': 'shipping_fee',
    '税费': 'tax_fee',
    '运费补贴': 'shipping_subsidy',
    '计划类型': 'plan_type',
    '商品来源': 'product_source',
    '订单来源.1': 'order_source_traffic',
    '订单类型': 'order_type',
}

MERCHANT_COLUMN_TYPES = {
    'order_id': 'TEXT',
    'product_name': 'TEXT',
    'product_id': 'TEXT',
    'order_status': 'TEXT',
    'unsettled_reason': 'TEXT',
    'issuing_institution': 'TEXT',
    'paid_amount': 'REAL',
    'service_fee_rate': 'TEXT',
    'estimated_service_income': 'REAL',
    'settlement_amount': 'REAL',
    'actual_service_income': 'REAL',
    'payment_time': 'TEXT',
    'received_time': 'TEXT',
    'settlement_time': 'TEXT',
    'final_payment_time': 'TEXT',
    'deposit_amount': 'REAL',
    'store_id': 'TEXT',
    'store_name': 'TEXT',
    'product_quantity': 'INTEGER',
    'group_campaign_id': 'TEXT',
    'order_source_purchase': 'TEXT',
    'payment_subsidy': 'REAL',
    'platform_subsidy': 'REAL',
    'influencer_subsidy': 'REAL',
    'shipping_fee': 'REAL',
    'tax_fee': 'REAL',
    'shipping_subsidy': 'REAL',
    'plan_type': 'TEXT',
    'product_source': 'TEXT',
    'order_source_traffic': 'TEXT',
    'order_type': 'TEXT',
}

MERCHANT_REQUIRED_COLUMNS = ['订单id', '商品id', '结算时间']
MERCHANT_DEDUP_KEY_COLUMNS = ['order_id', 'product_id', 'settlement_time', 'group_campaign_id']

MERCHANT_TEXT_SOURCE_COLUMNS = {
    '订单id', '商品id', '店铺id', '团长活动id',
}

# ==================== 数据状态表标识 ====================

DATA_STATUS_CONFIG = {
    'orders': {
        'table_name': '订单表',
        'date_field': 'order_submitted_at',
    },
    'fund_flow': {
        'table_name': '资金结算表',
        'date_field': 'settlement_time',
    },
    'commission': {
        'table_name': '佣金订单明细',
        'date_field': 'payment_time',
    },
    'merchant': {
        'table_name': '招商订单明细',
        'date_field': 'payment_time',
    },
}

# ==================== 导出字段配置 ====================

EXPORT_TABLE_CONFIG = {
    'orders': {
        'label': '订单表',
        'column_mapping': ORDERS_COLUMN_MAPPING,
        'column_types': ORDERS_COLUMN_TYPES,
        'date_field': 'order_submitted_at',
    },
    'fund_flow': {
        'label': '资金结算表',
        'column_mapping': FUND_FLOW_COLUMN_MAPPING,
        'column_types': FUND_FLOW_COLUMN_TYPES,
        'date_field': 'settlement_time',
    },
    'commission': {
        'label': '佣金订单明细',
        'column_mapping': COMMISSION_COLUMN_MAPPING,
        'column_types': COMMISSION_COLUMN_TYPES,
        'date_field': 'payment_time',
    },
    'merchant': {
        'label': '招商订单明细',
        'column_mapping': MERCHANT_COLUMN_MAPPING,
        'column_types': MERCHANT_COLUMN_TYPES,
        'date_field': 'payment_time',
    },
}
