"""快手美妆表结构定义。"""

ORDER_COLUMN_MAPPING = {
    '订单号': 'order_no',
    '赠品订单号': 'gift_order_no',
    '活动订单编号': 'activity_order_no',
    '订单创建时间': 'order_created_at',
    '订单支付时间': 'order_paid_at',
    '预售定金支付时间': 'presale_deposit_paid_at',
    '订单状态': 'order_status',
    '实付款': 'paid_amount',
    '快递费': 'shipping_fee',
    '店铺优惠': 'store_discount',
    '平台补贴': 'platform_subsidy',
    '主播补贴': 'streamer_subsidy',
    '混资活动优惠': 'mixed_activity_discount',
    '支付优惠': 'payment_discount',
    '支付方式': 'payment_method',
    '成交数量': 'deal_quantity',
    '买家留言': 'buyer_message',
    '账号类型': 'account_type',
    '账号明细': 'account_detail',
    '订单备注': 'order_remark',
    '旗帜颜色': 'flag_color',
    '售后状态': 'after_sales_status',
    '活动订单': 'activity_order',
    '预售/承诺发货时间': 'promised_ship_time',
    '订单载体': 'order_carrier',
    '商品名称': 'product_name',
    '商品ID': 'product_id',
    '商品规格': 'product_spec',
    'SKU编码': 'sku_code',
    '商品单价': 'product_unit_price',
    '渠道': 'channel',
    'CPS达人ID': 'cps_creator_id',
    'CPS达人昵称': 'cps_creator_nickname',
    '预估推广佣金': 'estimated_promotion_commission',
    '预估推广者分佣比例': 'estimated_promoter_commission_rate',
    '团长ID': 'leader_id',
    '团长昵称': 'leader_nickname',
    '快赚客ID': 'kuaizhuanke_id',
    '快赚客昵称': 'kuaizhuanke_nickname',
    '授权推广者ID': 'authorized_promoter_id',
    '授权推广者昵称': 'authorized_promoter_nickname',
    '收货人姓名': 'recipient_name',
    '收货人电话': 'recipient_phone',
    '收货地址-省': 'province',
    '收货地址-市': 'city',
    '收货地址-区': 'district',
    '收货地址-街道': 'street',
    '收货地址': 'recipient_address',
    '发货时间': 'shipped_at',
    '快递公司': 'logistics_company',
    '快递单号': 'tracking_no',
    '物流信息': 'logistics_info',
    '集运类型': 'consolidation_type',
    '直邮类型': 'direct_mail_type',
    '仓库名称': 'warehouse_name',
    '仓库地址': 'warehouse_address',
    '发货类型': 'shipping_type',
    '实名姓名': 'real_name',
    '服务门店ID': 'service_store_id',
    '服务门店名称': 'service_store_name',
    '服务门店地址': 'service_store_address',
    '国补/类国补/消费券': 'subsidy_coupon_info',
}

ORDER_REQUIRED_COLUMNS = ['订单号', '订单创建时间', '商品ID']

ORDER_COLUMN_TYPES = {
    'order_no': 'TEXT',
    'gift_order_no': 'TEXT',
    'activity_order_no': 'TEXT',
    'order_created_at': 'TEXT',
    'order_paid_at': 'TEXT',
    'presale_deposit_paid_at': 'TEXT',
    'order_status': 'TEXT',
    'paid_amount': 'REAL',
    'shipping_fee': 'REAL',
    'store_discount': 'REAL',
    'platform_subsidy': 'REAL',
    'streamer_subsidy': 'REAL',
    'mixed_activity_discount': 'REAL',
    'payment_discount': 'REAL',
    'payment_method': 'TEXT',
    'deal_quantity': 'INTEGER',
    'buyer_message': 'TEXT',
    'account_type': 'TEXT',
    'account_detail': 'TEXT',
    'order_remark': 'TEXT',
    'flag_color': 'TEXT',
    'after_sales_status': 'TEXT',
    'activity_order': 'TEXT',
    'promised_ship_time': 'TEXT',
    'order_carrier': 'TEXT',
    'product_name': 'TEXT',
    'product_id': 'TEXT',
    'product_spec': 'TEXT',
    'sku_code': 'TEXT',
    'product_unit_price': 'REAL',
    'channel': 'TEXT',
    'cps_creator_id': 'TEXT',
    'cps_creator_nickname': 'TEXT',
    'estimated_promotion_commission': 'REAL',
    'estimated_promoter_commission_rate': 'REAL',
    'leader_id': 'TEXT',
    'leader_nickname': 'TEXT',
    'kuaizhuanke_id': 'TEXT',
    'kuaizhuanke_nickname': 'TEXT',
    'authorized_promoter_id': 'TEXT',
    'authorized_promoter_nickname': 'TEXT',
    'recipient_name': 'TEXT',
    'recipient_phone': 'TEXT',
    'province': 'TEXT',
    'city': 'TEXT',
    'district': 'TEXT',
    'street': 'TEXT',
    'recipient_address': 'TEXT',
    'shipped_at': 'TEXT',
    'logistics_company': 'TEXT',
    'tracking_no': 'TEXT',
    'logistics_info': 'TEXT',
    'consolidation_type': 'TEXT',
    'direct_mail_type': 'TEXT',
    'warehouse_name': 'TEXT',
    'warehouse_address': 'TEXT',
    'shipping_type': 'TEXT',
    'real_name': 'TEXT',
    'service_store_id': 'TEXT',
    'service_store_name': 'TEXT',
    'service_store_address': 'TEXT',
    'subsidy_coupon_info': 'TEXT',
}

FUND_FLOW_COLUMN_MAPPING = {
    '订单号': 'order_no',
    '下单时间': 'order_created_at',
    '结算发起时间': 'settlement_started_at',
    '商品ID': 'product_id',
    '商品数量': 'product_quantity',
    '订单实付(元)': 'order_paid_amount',
    '政府补贴': 'government_subsidy',
    '支付营销补贴': 'payment_marketing_subsidy',
    '平台补贴(元)': 'platform_subsidy',
    '技术服务费(元)': 'technical_service_fee',
    '达人ID': 'creator_id',
    '推广者佣金(元)': 'creator_commission',
    '订单退款(元)': 'order_refund_amount',
    '支付营销回退（元）': 'payment_marketing_refund',
    '人民币结算金额(元)': 'actual_settlement_amount',
    '资金渠道': 'fund_channel',
    '结算状态': 'settlement_status',
    '结算币种': 'settlement_currency',
    '结算汇率': 'settlement_exchange_rate',
    '境外结算金额': 'overseas_settlement_amount',
    '结算批次号': 'settlement_batch_no',
    '结算时间': 'actual_settlement_time',
    '其他收费': 'other_fee_detail',
    '其他收费金额': 'other_fee',
    '商品名称': 'product_name',
    '团长id': 'leader_id',
    '团长佣金(元)': 'leader_commission',
}

FUND_FLOW_REQUIRED_COLUMNS = ['订单号', '商品ID', '结算时间']

FUND_FLOW_COLUMN_TYPES = {
    'order_no': 'TEXT',
    'order_created_at': 'TEXT',
    'settlement_started_at': 'TEXT',
    'product_id': 'TEXT',
    'product_quantity': 'INTEGER',
    'order_paid_amount': 'REAL',
    'government_subsidy': 'REAL',
    'payment_marketing_subsidy': 'REAL',
    'platform_subsidy': 'REAL',
    'technical_service_fee': 'REAL',
    'creator_id': 'TEXT',
    'creator_commission': 'REAL',
    'order_refund_amount': 'REAL',
    'payment_marketing_refund': 'REAL',
    'actual_settlement_amount': 'REAL',
    'fund_channel': 'TEXT',
    'settlement_status': 'TEXT',
    'settlement_currency': 'TEXT',
    'settlement_exchange_rate': 'REAL',
    'overseas_settlement_amount': 'REAL',
    'settlement_batch_no': 'TEXT',
    'actual_settlement_time': 'TEXT',
    'other_fee_detail': 'TEXT',
    'other_fee': 'REAL',
    'product_name': 'TEXT',
    'leader_id': 'TEXT',
    'leader_commission': 'REAL',
}

AFTER_SALES_COLUMN_MAPPING = {
    '售后单号': 'after_sales_no',
    '订单编号': 'order_no',
    '订单状态': 'order_status',
    '订单创建时间': 'order_created_at',
    '实付款': 'paid_amount',
    '快递费': 'shipping_fee',
    '商家实收金额': 'merchant_received_amount',
    '商品ID': 'product_id',
    '商品名称': 'product_name',
    'SKU编码': 'sku_code',
    '商品规格': 'product_spec',
    '买家ID': 'buyer_id',
    '买家昵称': 'buyer_nickname',
    '售后类型': 'after_sales_type',
    '退款金额': 'refund_amount',
    '售后状态': 'after_sales_status',
    '售后原因': 'after_sales_reason',
    '售后原因标签（二级）': 'after_sales_reason_tag_level2',
    '申请描述': 'apply_description',
    '售后申请时间': 'after_sales_apply_time',
    '售后完结时间': 'after_sales_finished_time',
    '超时时间': 'timeout_time',
    '是否ATOM处理': 'is_atom_processed',
    '退款方式': 'refund_method',
    '售后操作': 'after_sales_operation',
    '客服仲裁': 'customer_service_arbitration',
    '发货快递单号(如为西北订单，仅展示一段物流信息)': 'delivery_tracking_no',
    '发货快递公司(如为西北订单，仅展示一段物流信息)': 'delivery_logistics_company',
    '退货物流单号': 'return_tracking_no',
    '退货物流公司': 'return_logistics_company',
    '退货物流状态': 'return_logistics_status',
    '退货异常': 'return_abnormal',
    '商家退货地址': 'merchant_return_address',
    '商家退货联系人姓名': 'merchant_return_contact_name',
    '商家退货联系人电话': 'merchant_return_contact_phone',
    '换货物流单号': 'exchange_tracking_no',
    '换货物流公司': 'exchange_logistics_company',
    '换货商品信息': 'exchange_product_info',
    '操作人': 'operator',
    '旗帜颜色': 'flag_color',
    '插旗备注': 'flag_remark',
}

AFTER_SALES_REQUIRED_COLUMNS = ['售后单号', '售后申请时间']

AFTER_SALES_COLUMN_TYPES = {
    'after_sales_no': 'TEXT',
    'order_no': 'TEXT',
    'order_status': 'TEXT',
    'order_created_at': 'TEXT',
    'paid_amount': 'REAL',
    'shipping_fee': 'REAL',
    'merchant_received_amount': 'REAL',
    'product_id': 'TEXT',
    'product_name': 'TEXT',
    'sku_code': 'TEXT',
    'product_spec': 'TEXT',
    'buyer_id': 'TEXT',
    'buyer_nickname': 'TEXT',
    'after_sales_type': 'TEXT',
    'refund_amount': 'REAL',
    'after_sales_status': 'TEXT',
    'after_sales_reason': 'TEXT',
    'after_sales_reason_tag_level2': 'TEXT',
    'apply_description': 'TEXT',
    'after_sales_apply_time': 'TEXT',
    'after_sales_finished_time': 'TEXT',
    'timeout_time': 'TEXT',
    'is_atom_processed': 'TEXT',
    'refund_method': 'TEXT',
    'after_sales_operation': 'TEXT',
    'customer_service_arbitration': 'TEXT',
    'delivery_tracking_no': 'TEXT',
    'delivery_logistics_company': 'TEXT',
    'return_tracking_no': 'TEXT',
    'return_logistics_company': 'TEXT',
    'return_logistics_status': 'TEXT',
    'return_abnormal': 'TEXT',
    'merchant_return_address': 'TEXT',
    'merchant_return_contact_name': 'TEXT',
    'merchant_return_contact_phone': 'TEXT',
    'exchange_tracking_no': 'TEXT',
    'exchange_logistics_company': 'TEXT',
    'exchange_product_info': 'TEXT',
    'operator': 'TEXT',
    'flag_color': 'TEXT',
    'flag_remark': 'TEXT',
}

KUAISHOU_ORDER_TABLE_NAME = 'ks_meizhuang_orders'
KUAISHOU_FUND_FLOW_TABLE_NAME = 'ks_meizhuang_fund_flow'
KUAISHOU_AFTER_SALES_TABLE_NAME = 'ks_meizhuang_after_sales'

ORDER_DEDUP_KEY_COLUMNS = ['order_no', 'product_id', 'sku_code', 'product_spec']
FUND_FLOW_DEDUP_KEY_COLUMNS = [
    'order_no',
    'product_id',
    'actual_settlement_time',
    'actual_settlement_amount',
    'creator_commission',
    'other_fee',
]
AFTER_SALES_DEDUP_KEY_COLUMNS = ['after_sales_no']

DATA_STATUS_TABLE_NAME = 'ks_meizhuang_data_status'

DATA_STATUS_CONFIG = {
    'orders': {
        'table_name': '订单表',
        'source_table': KUAISHOU_ORDER_TABLE_NAME,
        'date_field': 'order_created_at',
    },
    'fund_flows': {
        'table_name': '资金流水表',
        'source_table': KUAISHOU_FUND_FLOW_TABLE_NAME,
        'date_field': 'actual_settlement_time',
    },
    'aftersales': {
        'table_name': '售后表',
        'source_table': KUAISHOU_AFTER_SALES_TABLE_NAME,
        'date_field': 'after_sales_apply_time',
    },
}

EXPORT_TABLE_CONFIG = {
    'orders': {
        'label': '订单表',
        'source_table': KUAISHOU_ORDER_TABLE_NAME,
        'date_field': 'order_created_at',
        'column_mapping': ORDER_COLUMN_MAPPING,
        'column_types': ORDER_COLUMN_TYPES,
    },
    'fund_flows': {
        'label': '资金流水表',
        'source_table': KUAISHOU_FUND_FLOW_TABLE_NAME,
        'date_field': 'actual_settlement_time',
        'column_mapping': FUND_FLOW_COLUMN_MAPPING,
        'column_types': FUND_FLOW_COLUMN_TYPES,
    },
    'aftersales': {
        'label': '售后表',
        'source_table': KUAISHOU_AFTER_SALES_TABLE_NAME,
        'date_field': 'after_sales_apply_time',
        'column_mapping': AFTER_SALES_COLUMN_MAPPING,
        'column_types': AFTER_SALES_COLUMN_TYPES,
    },
}
